[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
diesel = { version = "2.2.10", features = ["sqlite"] }
rocket = { version = "0.5.1", features = ["json", "serde_json"] }
rocket_okapi = { version = "0.9.0", features = ["swagger"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = "1.45.1"

