# backend/Rocket.toml

# Configurazione di default per lo sviluppo locale
[default]
address = "127.0.0.1"
port = 8000

# Configurazione per l'ambiente di produzione
# Questi valori verranno SOVRASCRITTI dalle variabili d'ambiente su Render
[release]
address = "0.0.0.0"
port = 8000 
